language: minimal

env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="

before_install:
  - cd ..
  # Display CPU and memory information on the Linux builds
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lscpu; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then free -m; fi
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  # Update conda
  - conda update --yes conda
  - conda info -a
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "rmg_dev@mit.edu"

install:
  # Clone RMG-Py and RMG-webstie
  - git clone https://github.com/ReactionMechanismGenerator/RMG-Py.git
  - git clone https://github.com/ReactionMechanismGenerator/RMG-database.git
  - export PYTHONPATH=$TRAVIS_BUILD_DIR/../RMG-Py:$PYTHONPATH
  - cd RMG-Py
  - conda env create -f environment.yml
  - source activate rmg_env
  - make
  - cd $TRAVIS_BUILD_DIR
  - conda env update
  - cp ./rmgweb/secretsettings.py.example ./rmgweb/secretsettings.py

script:
  - python manage.py test rmgweb.tests -v 2

